apiVersion: v1
kind: Service
metadata:
  name: mcp-server
  namespace: aub-clubs
spec:
  type: ClusterIP
  selector:
    app: mcp-server
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
