apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aub-clubs-runtime-secrets
  namespace: aub-clubs
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: aub-clubs-runtime-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: "{{ sharedVars.secretManagerEnvSecretName }}"
