// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

// Represents an AI automation script within a project.
// Scripts define reusable AI workflows and automations.
type AIScript struct {
	// Unique identifier for the script
	ID string `json:"id"`
	// Reference ID to the script's configuration
	ScriptConfigID string `json:"scriptConfigId"`
	// Creation date in string format
	Created string `json:"created"`
	// Identifier of the user who created the script
	CreatedBy string `json:"createdBy"`
	// Timestamp when the script was created
	CreatedAt time.Time `json:"createdAt"`
	// Timestamp when the script was last updated
	UpdatedAt time.Time `json:"updatedAt"`
	// ID of the project this script belongs to
	ProjectID string `json:"projectId"`
	// Reference to the parent project
	Project *Project `json:"project"`
}

type AgentRun struct {
	// Unique identifier for the agent run
	ID string `json:"id"`
	// Status of the agent run
	RunStatus string `json:"runStatus"`
	// Timestamp when the run was created
	CreatedAt time.Time `json:"createdAt"`
	// Timestamp when the run was last updated
	UpdatedAt time.Time `json:"updatedAt"`
	// ID of the project this run belongs to
	ProjectID string `json:"projectId"`
	// List of steps taken during this agent run
	Steps []*AgentStep `json:"steps"`
}

// Steps taken during an AI agent run within a project.
type AgentStep struct {
	// Unique identifier for the agent step
	ID string `json:"id"`
	// Name of the step
	StepName string `json:"stepName"`
	// Status of the step
	StepStatus string `json:"stepStatus"`
	// Details or output of the step
	StepOutput *string `json:"stepOutput,omitempty"`
	// Timestamp when the step was created
	CreatedAt time.Time `json:"createdAt"`
	// Timestamp when the step was last updated
	UpdatedAt time.Time `json:"updatedAt"`
	// ID of the agent run this step belongs to
	RunID string `json:"runId"`
}

// Root mutation type for AI IDE write operations.
// Access this via the aiIDEMutations field on the Mutation type.
type AiIDEMutations struct {
	// Create a new project with initial content
	CreateProject *Project `json:"createProject"`
	// Add a new message to a project's conversation
	CreateMessage *Message `json:"createMessage"`
	// Update file content within a project
	UpdateFilesContent []*File `json:"updateFilesContent"`
	// Enable AI in a project by setting isAIProject to true
	EnableAIInProject *Project `json:"enableAIInProject"`
	// Updates Script code without provisioning
	SetFilesContent []*File `json:"setFilesContent"`
	// Create Script
	CreateScript *AIScript `json:"createScript,omitempty"`
}

// Root query type for AI IDE read operations.
// Access this via the aiIDEQueries field on the Query type.
type AiIDEQueries struct {
	// Retrieve a specific project by its ID
	GetProject *Project `json:"getProject,omitempty"`
	// Get all messages for a specific project
	GetMessages []*Message `json:"getMessages"`
	// List all available projects
	GetProjects []*Project `json:"getProjects"`
	// Get all files for a specific project
	GetFiles []*File `json:"getFiles"`
	// Get all AI scripts for a specific project (NOTE: make sure to take the most recent script id)
	GetScripts []*AIScript `json:"getScripts"`
	// Get message chunks for a specific message
	GetMessageChunks []*MessageChunk `json:"getMessageChunks"`
	// Get agent runs for a specific project
	GetAgentRuns []*AgentRun `json:"getAgentRuns"`
	// Get steps for a specific agent run
	GetAgentSteps []*AgentStep `json:"getAgentSteps"`
}

// Represents a code file within a project.
// Files contain the actual source code and content managed by the AI IDE.
type File struct {
	// Unique identifier for the file
	ID string `json:"id"`
	// Name of the file including extension
	Name string `json:"name"`
	// Complete content of the file
	Content string `json:"content"`
	// File system path relative to the project root
	Path string `json:"path"`
	// ID of the project this file belongs to
	ProjectID string    `json:"projectId"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// Input type for updating file content within a project.
type FileContentInput struct {
	Path    string `json:"path"`
	Content string `json:"content"`
}

// Represents a conversation message within an AI IDE project.
// Messages form the conversation history between users and the AI assistant.
type Message struct {
	// Unique identifier for the message
	ID string `json:"id"`
	// Main content of the message
	Content string `json:"content"`
	// Role of the message sender (USER or ASSISTANT)
	Role MessageRole `json:"role"`
	// Type of message (RESULT or ERROR)
	Type MessageType `json:"type"`
	// Timestamp when the message was created
	CreatedAt time.Time `json:"createdAt"`
	// Timestamp when the message was last updated
	UpdatedAt time.Time `json:"updatedAt"`
	// ID of the project this message belongs to
	ProjectID string `json:"projectId"`
	// Reference to the parent project
	Project *Project `json:"project"`
	// List of chunks associated with the message
	Chunks []*MessageChunk `json:"chunks,omitempty"`
}

// Represents a chunk of a streamed message response.
type MessageChunk struct {
	// Unique identifier for the chunk
	ID string `json:"id"`
	// Response content of the chunk
	Response string `json:"response"`
	// Timestamp when the chunk was created
	CreatedAt time.Time `json:"createdAt"`
	// Timestamp when the chunk was last updated
	UpdatedAt time.Time `json:"updatedAt"`
	// ID of the message this chunk belongs to
	MessageID string `json:"messageId"`
	// Reference to the parent message
	Message *Message `json:"message"`
}

type Mutation struct {
}

// Represents an AI IDE project workspace.
// A project contains conversation messages, code files, and AI automation scripts.
type Project struct {
	// Unique identifier for the project
	ID string `json:"id"`
	// Human-readable name of the project
	Name string `json:"name"`
	// Name of the script linked to this project
	ScriptName string `json:"scriptName"`
	// Description of the script linked to this project
	ScriptDescription string `json:"scriptDescription"`
	// Is the project an AI Project
	IsAIProject bool `json:"isAIProject"`
	// Is the project awaiting script activation
	IsAwaitingScriptActivation bool `json:"isAwaitingScriptActivation"`
	// Timestamp when the project was created
	CreatedAt time.Time `json:"createdAt"`
	// Timestamp when the project was last updated
	UpdatedAt time.Time `json:"updatedAt"`
	// Type of the project (PROVISIONING or NORMAL)
	ProjectType ProjectType `json:"projectType"`
	// List of conversation messages in this project
	Messages []*Message `json:"messages"`
	// Code files associated with this project
	Code []*File `json:"code,omitempty"`
	// AI automation scripts associated with this project
	Scripts []*AIScript `json:"scripts,omitempty"`
	// AI agent runs associated with this project
	AgentRuns []*AgentRun `json:"agentRuns,omitempty"`
}

type Query struct {
}

// Input type for updating multiple files' content in a project.
type UpdateFilesContentInput struct {
	ProjectID   string              `json:"projectId"`
	Files       []*FileContentInput `json:"files"`
	DeleteFiles []string            `json:"deleteFiles,omitempty"`
}

// Input for attaching a script config to a project
type ScriptInput struct {
	ScriptConfigID *string `json:"scriptConfigId,omitempty"`
	Created        *string `json:"created,omitempty"`
	CreatedBy      *string `json:"createdBy,omitempty"`
	ProjectID      *string `json:"projectId,omitempty"`
}

// Input for initially setting the code.
type SetFilesContentInput struct {
	ProjectID string              `json:"projectId"`
	Files     []*FileContentInput `json:"files"`
}

// Defines the role of the message sender in a conversation.
type MessageRole string

const (
	// Message sent by the user
	MessageRoleUser MessageRole = "USER"
	// Message sent by the AI assistant
	MessageRoleAssistant MessageRole = "ASSISTANT"
)

var AllMessageRole = []MessageRole{
	MessageRoleUser,
	MessageRoleAssistant,
}

func (e MessageRole) IsValid() bool {
	switch e {
	case MessageRoleUser, MessageRoleAssistant:
		return true
	}
	return false
}

func (e MessageRole) String() string {
	return string(e)
}

func (e *MessageRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MessageRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MessageRole", str)
	}
	return nil
}

func (e MessageRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MessageRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MessageRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Categorizes the type of message content.
type MessageType string

const (
	// Successful operation result or normal response
	MessageTypeResult MessageType = "RESULT"
	// Error message or failure notification
	MessageTypeError MessageType = "ERROR"
)

var AllMessageType = []MessageType{
	MessageTypeResult,
	MessageTypeError,
}

func (e MessageType) IsValid() bool {
	switch e {
	case MessageTypeResult, MessageTypeError:
		return true
	}
	return false
}

func (e MessageType) String() string {
	return string(e)
}

func (e *MessageType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MessageType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MessageType", str)
	}
	return nil
}

func (e MessageType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MessageType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MessageType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Defines the type of AI IDE project.
type ProjectType string

const (
	// Project focused on provisioning resources
	ProjectTypeProvisioning ProjectType = "PROVISIONING"
	// Normal project
	ProjectTypeNormal ProjectType = "NORMAL"
)

var AllProjectType = []ProjectType{
	ProjectTypeProvisioning,
	ProjectTypeNormal,
}

func (e ProjectType) IsValid() bool {
	switch e {
	case ProjectTypeProvisioning, ProjectTypeNormal:
		return true
	}
	return false
}

func (e ProjectType) String() string {
	return string(e)
}

func (e *ProjectType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ProjectType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ProjectType", str)
	}
	return nil
}

func (e ProjectType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ProjectType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ProjectType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
