package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"ai_ide_gql/graph/model"
	"bytes"
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"strconv"
	"strings"
	"time"

	"github.com/google/uuid"
	_ "github.com/joho/godotenv/autoload"
	"github.com/kpechenenko/rword"
)

// CreateProject is the resolver for the createProject field.
func (r *aiIDEMutationsResolver) CreateProject(ctx context.Context, obj *model.AiIDEMutations, content *string, scriptName *string, scriptDescription *string, isAIProject *bool, newProject *bool) (*model.Project, error) {
	fmt.Printf("[CreateProject] Starting project creation.\n")

	if (isAIProject != nil && !*isAIProject || isAIProject == nil) && (scriptName == nil || scriptDescription == nil) {
		fmt.Println("[CreateProject] Error: scriptName and scriptDescription is required for non-AI projects")
		return nil, fmt.Errorf("scriptName and scriptDescription are required for non-AI projects")
	}

	if isAIProject != nil && *isAIProject && (content == nil || len(*content) == 0) {
		fmt.Println("[CreateProject] Error: content is required for AI projects")
		return nil, fmt.Errorf("content is required for AI projects")
	}

	if newProject != nil && *newProject && scriptName != nil {
		fmt.Printf("[CreateProject] Checking provided scriptName: %s\n", *scriptName)
		base_url := os.Getenv("AI_IDE_BASE_URL")
		url := base_url + "/api/scripts/validatescriptname"
		fmt.Printf("[CreateProject] Calling AI validate script name endpoint: %s\n", url)

		payload := map[string]string{
			"scriptName": *scriptName,
		}

		jsonData, err := json.Marshal(payload)
		if err != nil {
			fmt.Printf("[CreateProject] Error marshaling payload: %v\n", err)
			return nil, err
		}

		fmt.Printf("[CreateProject] Sending POST request to AI agent\n")
		resp, err := http.Post(url, "application/json", bytes.NewBuffer(jsonData))
		if err != nil {
			fmt.Printf("[CreateProject] HTTP error: %v\n", err)
			return nil, err
		}
		fmt.Printf("[CreateProject] Received response with status: %d\n", resp.StatusCode)
		defer resp.Body.Close()

		data, err := io.ReadAll(resp.Body)
		if err != nil {
			fmt.Printf("[CreateProject] Error reading response body: %v\n", err)
			return nil, err
		}

		var result map[string]bool
		err = json.Unmarshal(data, &result)
		if err != nil {
			fmt.Printf("[CreateProject] Error unmarshaling response: %v\n", err)
			return nil, err
		}

		if valid := result["isValid"]; !valid {
			fmt.Printf("[CreateProject] Script name validation failed: %s\n", *scriptName)
			return nil, fmt.Errorf("Script name is invalid or already taken")
		}
		fmt.Printf("[CreateProject] Script name validated successfully: %s\n", *scriptName)
	}

	var proj model.Project

	gen, err := rword.New()

	if err != nil {
		fmt.Printf("[CreateProject] Error initializing rword: %v\n", err)
		return nil, fmt.Errorf("failed to init rword: %w", err)
	}

	words := gen.WordList(2)
	newProjectId := uuid.New().String()
	name := strings.ToLower(strings.Join(words, "-") + "-" + newProjectId[:8])
	fmt.Printf("[CreateProject] Generated project name: %s, ID: %s\n", name, newProjectId)
	timeNow := time.Now().UTC()

	cols := []string{`"id"`, `"name"`, `"createdAt"`, `"updatedAt"`}
	vals := []string{"$1", "$2", "$3", "$4"}
	args := []any{newProjectId, name, timeNow, timeNow}

	i := 5

	if scriptName != nil {
		cols = append(cols, `"scriptName"`)
		vals = append(vals, fmt.Sprintf("$%d", i))
		args = append(args, *scriptName)
		i++
	}

	if scriptDescription != nil {
		cols = append(cols, `"scriptDescription"`)
		vals = append(vals, fmt.Sprintf("$%d", i))
		args = append(args, *scriptDescription)
		i++
	}

	if isAIProject != nil && *isAIProject {
		cols = append(cols, `"isAIProject"`)
		vals = append(vals, fmt.Sprintf("$%d", i))
		args = append(args, *isAIProject)
		i++
	}

	q := fmt.Sprintf(`
	INSERT INTO "AIIDEProject" (%s)
	VALUES (%s)
	RETURNING "id", "name", "scriptName", "scriptDescription", "projectType", "isAIProject", "isAwaitingScriptActivation", "createdAt", "updatedAt";
	`,
		strings.Join(cols, ", "),
		strings.Join(vals, ", "),
	)

	fmt.Printf("[CreateProject] Inserting project into database: %s\n", newProjectId)

	var scriptNameNull, scriptDescriptionNull sql.NullString
	err = r.aiIdeDB.QueryRowContext(ctx, q, args...).Scan(
		&proj.ID,
		&proj.Name,
		&scriptNameNull,
		&scriptDescriptionNull,
		&proj.ProjectType,
		&proj.IsAIProject,
		&proj.IsAwaitingScriptActivation,
		&proj.CreatedAt,
		&proj.UpdatedAt,
	)

	if scriptNameNull.Valid {
		proj.ScriptName = scriptNameNull.String
	}
	if scriptDescriptionNull.Valid {
		proj.ScriptDescription = scriptDescriptionNull.String
	}

	if err != nil {
		fmt.Printf("[CreateProject] Database error: %v\n", err)
		return nil, err
	}

	if isAIProject != nil && *isAIProject {
		fmt.Printf("[CreateProject] Creating initial message for project: %s\n", newProjectId)
		msg, err := r.CreateMessage(ctx, obj, newProjectId, *content)
		if err != nil {
			fmt.Printf("[CreateProject] Error creating initial message: %v\n", err)
			return nil, err
		}
		proj.Messages = []*model.Message{msg}
	}

	fmt.Printf("[CreateProject] Project creation completed: %s\n", proj.ID)
	return &proj, nil
}

// CreateMessage is the resolver for the createMessage field.
func (r *aiIDEMutationsResolver) CreateMessage(ctx context.Context, obj *model.AiIDEMutations, projectID string, content string) (*model.Message, error) {
	fmt.Printf("[CreateMessage] Starting message creation for project: %s, content length: %d\n", projectID, len(content))
	// Use queries resolver to call GetProject
	if projectID == "" || content == "" {
		fmt.Println("[CreateMessage] Error: projectId or content is empty")
		return nil, fmt.Errorf("projectId and content are required")
	}

	fmt.Printf("[CreateMessage] Fetching project details\n")
	queriesResolver := &aiIDEQueriesResolver{r.Resolver}
	project, _ := queriesResolver.GetProject(ctx, nil, projectID)

	if !project.IsAIProject {
		fmt.Printf("[CreateMessage] Project is not AI project, skipping AI agent call: %s\n", projectID)
		return nil, fmt.Errorf("project is not an AI project")
	}

	const q = `
    INSERT INTO "AIIDEMessage" ("id", "content", "role", "type", "createdAt", "updatedAt", "projectId")
    VALUES ($1, $2, $3::"MessageRole", $4::"MessageType", $5, $6, $7)
    RETURNING "id", "content", "role", "type", "projectId", "createdAt", "updatedAt";
    `

	newMessageId := uuid.New().String()
	timeNow := time.Now().UTC()
	fmt.Printf("[CreateMessage] Generated message ID: %s\n", newMessageId)

	var msg model.Message

	fmt.Printf("[CreateMessage] Inserting message into database\n")
	err := r.aiIdeDB.QueryRowContext(ctx, q, newMessageId, content, "USER", "RESULT", timeNow, timeNow, projectID).Scan(&msg.ID, &msg.Content, &msg.Role, &msg.Type, &msg.ProjectID, &msg.CreatedAt, &msg.UpdatedAt)
	if err != nil {
		fmt.Printf("[CreateMessage] Database error: %v\n", err)
		return nil, err
	}
	fmt.Printf("[CreateMessage] Message stored in database: %s\n", msg.ID)
	base_url := os.Getenv("AI_IDE_BASE_URL")
	url := base_url + "/api/agents/run"
	fmt.Printf("[CreateMessage] Calling AI agent endpoint: %s\n", url)

	payload := map[string]string{
		"message":   content,
		"projectId": projectID,
	}

	jsonData, err := json.Marshal(payload)
	if err != nil {
		fmt.Printf("[CreateMessage] Error marshaling payload: %v\n", err)
		return nil, err
	}

	fmt.Printf("[CreateMessage] Sending POST request to AI agent\n")
	resp, err := http.Post(url, "application/json", bytes.NewBuffer(jsonData))
	if err != nil {
		fmt.Printf("[CreateMessage] HTTP error: %v\n", err)
		return nil, err
	}
	fmt.Printf("[CreateMessage] Received response with status: %d\n", resp.StatusCode)
	defer resp.Body.Close()

	_, err = io.ReadAll(resp.Body)
	if err != nil {
		fmt.Printf("[CreateMessage] Error reading response body: %v\n", err)
		return nil, err
	}
	fmt.Printf("[CreateMessage] Message creation completed successfully: %s\n", msg.ID)

	return &msg, nil
}

// UpdateFilesContent is the resolver for the updateFilesContent field.
func (r *aiIDEMutationsResolver) UpdateFilesContent(ctx context.Context, obj *model.AiIDEMutations, input model.UpdateFilesContentInput) ([]*model.File, error) {
	fmt.Printf("[UpdateFilesContent] Starting file update for project: %s, files count: %d, delete count: %d\n", input.ProjectID, len(input.Files), len(input.DeleteFiles))
	base_url := os.Getenv("AI_IDE_BASE_URL")
	url := base_url + "/api/scripts/update"
	fmt.Printf("[UpdateFilesContent] Calling update endpoint: %s\n", url)

	payload := map[string]any{
		"files":       input.Files,
		"projectId":   input.ProjectID,
		"deleteFiles": input.DeleteFiles,
	}

	jsonData, err := json.Marshal(payload)
	if err != nil {
		fmt.Printf("[UpdateFilesContent] Error marshaling payload: %v\n", err)
		return nil, err
	}

	fmt.Printf("[UpdateFilesContent] Sending POST request\n")
	resp, err := http.Post(url, "application/json", bytes.NewBuffer(jsonData))
	if err != nil {
		fmt.Printf("[UpdateFilesContent] HTTP error: %v\n", err)
		return nil, err
	}
	fmt.Printf("[UpdateFilesContent] Received response with status: %d\n", resp.StatusCode)
	defer resp.Body.Close()

	_, err = io.ReadAll(resp.Body)
	if err != nil {
		fmt.Printf("[UpdateFilesContent] Error reading response body: %v\n", err)
		return nil, err
	}

	// Use queries resolver to call GetFiles
	fmt.Printf("[UpdateFilesContent] Fetching updated files list\n")
	queriesResolver := &aiIDEQueriesResolver{r.Resolver}
	return queriesResolver.GetFiles(ctx, nil, input.ProjectID)
}

// EnableAIInProject is the resolver for the enableAIInProject field.
func (r *aiIDEMutationsResolver) EnableAIInProject(ctx context.Context, obj *model.AiIDEMutations, projectID string) (*model.Project, error) {
	fmt.Printf("[EnableAIInProject] Enabling AI in project: %s\n", projectID)
	if projectID == "" {
		fmt.Println("[EnableAIInProject] Error: projectId is empty")
		return nil, fmt.Errorf("projectId is required")
	}

	const q = `
				UPDATE "AIIDEProject"
				SET "isAIProject" = TRUE, "updatedAt" = $2
				WHERE "id" = $1
				RETURNING "id", "name", "scriptName", "scriptDescription", "projectType", "isAIProject", "isAwaitingScriptActivation", "createdAt", "updatedAt";
		`
	var proj model.Project
	timeNow := time.Now().UTC()
	err := r.aiIdeDB.QueryRowContext(ctx, q, projectID, timeNow).Scan(&proj.ID, &proj.Name, &proj.ScriptName, &proj.ScriptDescription, &proj.ProjectType, &proj.IsAIProject, &proj.IsAwaitingScriptActivation, &proj.CreatedAt, &proj.UpdatedAt)
	if err != nil {
		fmt.Printf("[EnableAIInProject] Database error: %v\n", err)
		return nil, err
	}
	fmt.Printf("[EnableAIInProject] AI enabled for project: %s\n", proj.ID)
	return &proj, nil
}

// SetFilesContent is the resolver for the setFilesContent field.
func (r *aiIDEMutationsResolver) SetFilesContent(ctx context.Context, obj *model.AiIDEMutations, input model.SetFilesContentInput) ([]*model.File, error) {
	fmt.Printf("[SetFilesContent] Starting set files content for project: %s, files count: %d\n", input.ProjectID, len(input.Files))

	if input.ProjectID == "" {
		fmt.Println("[SetFilesContent] Error: projectId is empty")
		return nil, fmt.Errorf("projectId is required")
	}

	timeNow := time.Now().UTC()

	// Begin transaction
	tx, err := r.aiIdeDB.BeginTx(ctx, nil)
	if err != nil {
		fmt.Printf("[SetFilesContent] Error beginning transaction: %v\n", err)
		return nil, err
	}
	defer tx.Rollback()

	for _, fileInput := range input.Files {
		// simple name extraction from path
		parts := strings.Split(fileInput.Path, "/")
		name := parts[len(parts)-1]

		updateQ := `
            UPDATE "AIIDEFile"
            SET "content" = $1, "updatedAt" = $2, "name" = $3
            WHERE "projectId" = $4 AND "path" = $5
            RETURNING "id"
        `

		var id string
		err := tx.QueryRowContext(ctx, updateQ, fileInput.Content, timeNow, name, input.ProjectID, fileInput.Path).Scan(&id)

		if err != nil {
			if err == sql.ErrNoRows {
				// Insert
				insertQ := `
                    INSERT INTO "AIIDEFile" ("id", "name", "content", "path", "createdAt", "updatedAt", "projectId")
                    VALUES ($1, $2, $3, $4, $5, $6, $7)
                `
				newID := uuid.New().String()
				_, err = tx.ExecContext(ctx, insertQ, newID, name, fileInput.Content, fileInput.Path, timeNow, timeNow, input.ProjectID)
				if err != nil {
					fmt.Printf("[SetFilesContent] Insert error for path %s: %v\n", fileInput.Path, err)
					return nil, err
				}
				fmt.Printf("[SetFilesContent] Inserted new file: %s (path: %s)\n", newID, fileInput.Path)
			} else {
				fmt.Printf("[SetFilesContent] Update error for path %s: %v\n", fileInput.Path, err)
				return nil, err
			}
		} else {
			fmt.Printf("[SetFilesContent] Updated existing file: %s (path: %s)\n", id, fileInput.Path)
		}
	}

	if err := tx.Commit(); err != nil {
		fmt.Printf("[SetFilesContent] Error committing transaction: %v\n", err)
		return nil, err
	}

	fmt.Printf("[SetFilesContent] Fetching all files for project\n")
	queriesResolver := &aiIDEQueriesResolver{r.Resolver}
	return queriesResolver.GetFiles(ctx, nil, input.ProjectID)
}

// CreateScript is the resolver for the createScript field.
func (r *aiIDEMutationsResolver) CreateScript(ctx context.Context, obj *model.AiIDEMutations, input *model.ScriptInput) (*model.AIScript, error) {
	fmt.Printf("[CreateScript] Starting script creation for project: %v\n", input.ProjectID)

	if input.ProjectID == nil || *input.ProjectID == "" {
		fmt.Println("[CreateScript] Error: projectId is empty")
		return nil, fmt.Errorf("projectId is required")
	}

	newID := uuid.New().String()
	timeNow := time.Now().UTC()

	var scriptConfigID string
	if input.ScriptConfigID != nil {
		scriptConfigID = *input.ScriptConfigID
	}

	var created int64
	if input.Created != nil && *input.Created != "" {
		// Try parsing as int64 (timestamp)
		if val, err := strconv.ParseInt(*input.Created, 10, 64); err == nil {
			created = val
		} else {
			fmt.Printf("[CreateScript] Warning: could not parse created '%s' as number, defaulting to 0\n", *input.Created)
			created = 0
		}
	} else {
		created = 0
	}

	var createdBy string
	if input.CreatedBy != nil {
		createdBy = *input.CreatedBy
	}

	const q = `
		INSERT INTO "AIIDEAIScript" ("id", "scriptConfigId", "created", "createdBy", "createdAt", "updatedAt", "projectId")
		VALUES ($1, $2, $3, $4, $5, $6, $7)
		RETURNING "id", "scriptConfigId", "created", "createdBy", "createdAt", "updatedAt", "projectId"
	`

	var script model.AIScript
	err := r.aiIdeDB.QueryRowContext(ctx, q,
		newID,
		scriptConfigID,
		created,
		createdBy,
		timeNow,
		timeNow,
		*input.ProjectID,
	).Scan(
		&script.ID,
		&script.ScriptConfigID,
		&script.Created,
		&script.CreatedBy,
		&script.CreatedAt,
		&script.UpdatedAt,
		&script.ProjectID,
	)

	if err != nil {
		fmt.Printf("[CreateScript] Database error: %v\n", err)
		return nil, err
	}

	fmt.Printf("[CreateScript] Script created: %s\n", script.ID)
	return &script, nil
}

// GetProject is the resolver for the getProject field.
func (r *aiIDEQueriesResolver) GetProject(ctx context.Context, obj *model.AiIDEQueries, projectID string) (*model.Project, error) {
	fmt.Printf("[GetProject] Fetching project: %s\n", projectID)
	if projectID == "" {
		fmt.Println("[GetProject] Error: projectId is empty")
		return nil, fmt.Errorf("projectId is required")
	}

	const q = `
        SELECT
            p."id", p."name", COALESCE(p."scriptName", '') AS "scriptName", COALESCE(p."scriptDescription", '') AS "scriptDescription", p."isAIProject", p."isAwaitingScriptActivation", p."createdAt", p."updatedAt", p."projectType"
        FROM "AIIDEProject" p
        WHERE p."id" = $1
    `
	var proj model.Project

	err := r.aiIdeDB.QueryRowContext(ctx, q, projectID).Scan(&proj.ID, &proj.Name, &proj.ScriptName, &proj.ScriptDescription, &proj.IsAIProject, &proj.IsAwaitingScriptActivation, &proj.CreatedAt, &proj.UpdatedAt, &proj.ProjectType)

	if err != nil {
		if err == sql.ErrNoRows {
			fmt.Printf("[GetProject] Project not found: %s\n", projectID)
			return nil, nil
		}
		fmt.Printf("[GetProject] Database error: %v\n", err)
		return nil, err
	}
	fmt.Printf("[GetProject] Project found: %s (name: %s)\n", proj.ID, proj.Name)

	return &proj, nil
}

// GetMessages is the resolver for the getMessages field.
func (r *aiIDEQueriesResolver) GetMessages(ctx context.Context, obj *model.AiIDEQueries, projectID string) ([]*model.Message, error) {
	fmt.Printf("[GetMessages] Fetching messages for project: %s\n", projectID)
	if projectID == "" {
		fmt.Println("[GetMessages] Error: projectId is empty")
		return nil, fmt.Errorf("projectId is required")
	}

	fmt.Printf("[GetMessages] Fetching project details\n")
	project, _ := r.GetProject(ctx, nil, projectID)

	if !project.IsAIProject {
		fmt.Printf("[CreateMessage] Project is not AI project, skipping AI agent call: %s\n", projectID)
		return nil, fmt.Errorf("project is not an AI project")
	}

	const q = `
        SELECT
            m."id", m."content", m."role", m."type", m."createdAt", m."updatedAt", m."projectId"
        FROM "AIIDEMessage" m
        WHERE m."projectId" = $1
        ORDER BY m."updatedAt" ASC
    `
	rows, err := r.aiIdeDB.QueryContext(ctx, q, projectID)
	if err != nil {
		fmt.Printf("[GetMessages] Database error: %v\n", err)
		return nil, err
	}
	defer rows.Close()

	var out []*model.Message

	for rows.Next() {
		var (
			msg model.Message
		)

		if err := rows.Scan(
			&msg.ID, &msg.Content, &msg.Role, &msg.Type, &msg.CreatedAt, &msg.UpdatedAt, &msg.ProjectID,
		); err != nil {
			fmt.Printf("[GetMessages] Error scanning row: %v\n", err)
			return nil, err
		}

		out = append(out, &msg)
	}
	fmt.Printf("[GetMessages] Returning %d messages\n", len(out))
	return out, rows.Err()
}

// GetProjects is the resolver for the getProjects field.
func (r *aiIDEQueriesResolver) GetProjects(ctx context.Context, obj *model.AiIDEQueries) ([]*model.Project, error) {
	fmt.Println("[GetProjects] Fetching all projects")
	const q = `
        SELECT
        	p."id", p."name", COALESCE(p."scriptName", '') AS "scriptName", COALESCE(p."scriptDescription", '') AS "scriptDescription", p."isAIProject", p."isAwaitingScriptActivation", p."createdAt", p."updatedAt", p."projectType"
        FROM "AIIDEProject" p
        ORDER BY p."updatedAt" ASC
    `
	rows, err := r.aiIdeDB.QueryContext(ctx, q)
	if err != nil {
		fmt.Printf("[GetProjects] Database error: %v\n", err)
		return nil, err
	}
	defer rows.Close()

	var out []*model.Project

	for rows.Next() {
		var (
			proj model.Project
		)

		if err := rows.Scan(
			&proj.ID, &proj.Name, &proj.ScriptName, &proj.ScriptDescription, &proj.IsAIProject, &proj.IsAwaitingScriptActivation, &proj.CreatedAt, &proj.UpdatedAt, &proj.ProjectType,
		); err != nil {
			fmt.Printf("[GetProjects] Error scanning row: %v\n", err)
			return nil, err
		}

		out = append(out, &proj)
	}
	fmt.Printf("[GetProjects] Returning %d projects\n", len(out))
	return out, rows.Err()
}

// GetFiles is the resolver for the getFiles field.
func (r *aiIDEQueriesResolver) GetFiles(ctx context.Context, obj *model.AiIDEQueries, projectID string) ([]*model.File, error) {
	fmt.Printf("[GetFiles] Fetching files for project: %s\n", projectID)
	if projectID == "" {
		fmt.Println("[GetFiles] Error: projectId is empty")
		return nil, fmt.Errorf("projectId is required")
	}

	const q = `
				SELECT
						f."id", f."name", f."content", f."path", f."createdAt", f."updatedAt", f."projectId"
				FROM "AIIDEFile" f
				WHERE f."projectId" = $1
				ORDER BY f."updatedAt" ASC
		`
	rows, err := r.aiIdeDB.QueryContext(ctx, q, projectID)
	if err != nil {
		fmt.Printf("[GetFiles] Database error: %v\n", err)
		return nil, err
	}
	defer rows.Close()

	var out []*model.File

	for rows.Next() {
		var (
			file model.File
		)

		if err := rows.Scan(
			&file.ID, &file.Name, &file.Content, &file.Path, &file.CreatedAt, &file.UpdatedAt, &file.ProjectID,
		); err != nil {
			fmt.Printf("[GetFiles] Error scanning row: %v\n", err)
			return nil, err
		}

		out = append(out, &file)
	}
	fmt.Printf("[GetFiles] Returning %d files\n", len(out))
	return out, rows.Err()
}

// GetScripts is the resolver for the getScripts field.
func (r *aiIDEQueriesResolver) GetScripts(ctx context.Context, obj *model.AiIDEQueries, projectID string) ([]*model.AIScript, error) {
	fmt.Printf("[GetScripts] Fetching scripts for project: %s\n", projectID)
	if projectID == "" {
		fmt.Println("[GetScripts] Error: projectId is empty")
		return nil, fmt.Errorf("projectId is required")
	}

	const q = `
				SELECT
						s."id", s."scriptConfigId", s."created", s."createdBy", s."createdAt", s."updatedAt", s."projectId"
				FROM "AIIDEAIScript" s
				WHERE s."projectId" = $1
				ORDER BY s."updatedAt" ASC
		`
	rows, err := r.aiIdeDB.QueryContext(ctx, q, projectID)
	if err != nil {
		fmt.Printf("[GetScripts] Database error: %v\n", err)
		return nil, err
	}
	defer rows.Close()

	var out []*model.AIScript

	for rows.Next() {
		var (
			script model.AIScript
		)

		if err := rows.Scan(
			&script.ID, &script.ScriptConfigID, &script.Created, &script.CreatedBy, &script.CreatedAt, &script.UpdatedAt, &script.ProjectID,
		); err != nil {
			fmt.Printf("[GetScripts] Error scanning row: %v\n", err)
			return nil, err
		}

		out = append(out, &script)
	}
	fmt.Printf("[GetScripts] Returning %d scripts\n", len(out))
	return out, rows.Err()
}

// GetMessageChunks is the resolver for the getMessageChunks field.
func (r *aiIDEQueriesResolver) GetMessageChunks(ctx context.Context, obj *model.AiIDEQueries, messageID string) ([]*model.MessageChunk, error) {
	fmt.Printf("[GetMessageChunks] Fetching chunks for message: %s\n", messageID)
	if messageID == "" {
		fmt.Println("[GetMessageChunks] Error: messageId is empty")
		return nil, fmt.Errorf("messageId is required")
	}

	const q = `
		SELECT
			c."id", c."response", c."createdAt", c."updatedAt", c."messageId"
		FROM "AIIDEMessageChunk" c
		WHERE c."messageId" = $1
		ORDER BY c."createdAt" ASC
	`
	rows, err := r.aiIdeDB.QueryContext(ctx, q, messageID)
	if err != nil {
		fmt.Printf("[GetMessageChunks] Database error: %v\n", err)
		return nil, err
	}
	defer rows.Close()

	var out []*model.MessageChunk

	for rows.Next() {
		var (
			chunk model.MessageChunk
		)

		if err := rows.Scan(
			&chunk.ID, &chunk.Response, &chunk.CreatedAt, &chunk.UpdatedAt, &chunk.MessageID,
		); err != nil {
			fmt.Printf("[GetMessageChunks] Error scanning row: %v\n", err)
			return nil, err
		}

		out = append(out, &chunk)
	}
	fmt.Printf("[GetMessageChunks] Returning %d chunks\n", len(out))
	return out, rows.Err()
}

// GetAgentRuns is the resolver for the getAgentRuns field.
func (r *aiIDEQueriesResolver) GetAgentRuns(ctx context.Context, obj *model.AiIDEQueries, projectID string) ([]*model.AgentRun, error) {
	fmt.Printf("[GetAgentRuns] Fetching agent runs for project: %s\n", projectID)
	if projectID == "" {
		fmt.Println("[GetAgentRuns] Error: projectId is empty")
		return nil, fmt.Errorf("projectId is required")
	}

	const q = `
		SELECT
			r."id", r."runStatus", r."createdAt", r."updatedAt", r."projectId"
		FROM "AIIDEAgentRun" r
		WHERE r."projectId" = $1
		ORDER BY r."createdAt" DESC
	`
	rows, err := r.aiIdeDB.QueryContext(ctx, q, projectID)
	if err != nil {
		fmt.Printf("[GetAgentRuns] Database error: %v\n", err)
		return nil, err
	}
	defer rows.Close()

	var out []*model.AgentRun

	for rows.Next() {
		var (
			run model.AgentRun
		)

		if err := rows.Scan(
			&run.ID, &run.RunStatus, &run.CreatedAt, &run.UpdatedAt, &run.ProjectID,
		); err != nil {
			fmt.Printf("[GetAgentRuns] Error scanning row: %v\n", err)
			return nil, err
		}

		out = append(out, &run)
	}
	fmt.Printf("[GetAgentRuns] Returning %d runs\n", len(out))
	return out, rows.Err()
}

// GetAgentSteps is the resolver for the getAgentSteps field.
func (r *aiIDEQueriesResolver) GetAgentSteps(ctx context.Context, obj *model.AiIDEQueries, runID string) ([]*model.AgentStep, error) {
	fmt.Printf("[GetAgentSteps] Fetching steps for run: %s\n", runID)
	if runID == "" {
		fmt.Println("[GetAgentSteps] Error: runId is empty")
		return nil, fmt.Errorf("runId is required")
	}

	const q = `
		SELECT
			s."id", s."stepName", s."stepStatus", s."stepOutput", s."createdAt", s."updatedAt", s."runId"
		FROM "AIIDEAgentStep" s
		WHERE s."runId" = $1
		ORDER BY s."createdAt" ASC
	`
	rows, err := r.aiIdeDB.QueryContext(ctx, q, runID)
	if err != nil {
		fmt.Printf("[GetAgentSteps] Database error: %v\n", err)
		return nil, err
	}
	defer rows.Close()

	var out []*model.AgentStep

	for rows.Next() {
		var (
			step       model.AgentStep
			stepOutput sql.NullString
		)

		if err := rows.Scan(
			&step.ID, &step.StepName, &step.StepStatus, &stepOutput, &step.CreatedAt, &step.UpdatedAt, &step.RunID,
		); err != nil {
			fmt.Printf("[GetAgentSteps] Error scanning row: %v\n", err)
			return nil, err
		}

		if stepOutput.Valid {
			step.StepOutput = &stepOutput.String
		}

		out = append(out, &step)
	}
	fmt.Printf("[GetAgentSteps] Returning %d steps\n", len(out))
	return out, rows.Err()
}

// AiIDEMutations is the resolver for the aiIDEMutations field.
func (r *mutationResolver) AiIDEMutations(ctx context.Context) (*model.AiIDEMutations, error) {
	return &model.AiIDEMutations{}, nil
}

// AiIDEQueries is the resolver for the aiIDEQueries field.
func (r *queryResolver) AiIDEQueries(ctx context.Context) (*model.AiIDEQueries, error) {
	return &model.AiIDEQueries{}, nil
}

// AiIDEMutations returns AiIDEMutationsResolver implementation.
func (r *Resolver) AiIDEMutations() AiIDEMutationsResolver { return &aiIDEMutationsResolver{r} }

// AiIDEQueries returns AiIDEQueriesResolver implementation.
func (r *Resolver) AiIDEQueries() AiIDEQueriesResolver { return &aiIDEQueriesResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type aiIDEMutationsResolver struct{ *Resolver }
type aiIDEQueriesResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
