targets:
  - name: staging
    args:
      environment: staging
      environmentType: non-prod
    # Adding a context to .kluctl.yaml helps prevent accidentally deploying to the wrong cluster!
    context: gke_project-b2a5c546-f972-43e5-954_us-central1-a_aub-clubs-app-staging

  - name: production
    args:
      environment: production
      environmentType: prod
    # Adding a context to .kluctl.yaml helps prevent accidentally deploying to the wrong cluster!
    context: gke_project-b2a5c546-f972-43e5-954_us-central1-a_aub-clubs-app

args:
  - name: environment
  - name: environmentType

discriminator: kluctl-{{ target.name }}
