vars:
  - file: config/{{ args.environment }}.yaml

deployments:
  - path: namespaces
  - barrier: true
  - include: third-party
  - barrier: true # runtime secrets depend on External Secrets being installed
  - include: services

commonLabels:
  devopsdirective.com/course: "kubernetes-course"
