version: "3"

env:
  CLUSTER_NAME: aub-clubs-app
  GCP_REGION: us-central1
  GCP_ZONE: us-central1-a
  CLUSTER_NAME_STAGING: aub-clubs-app-staging

tasks:
  helm-pull:
    cmds:
      - kluctl helm-pull
    desc: "Pre-pull helm charts"

  render-staging:
    cmds:
      - kluctl render -t staging --print-all | yq
    desc: "Render resource yaml with staging values"

  deploy-staging:
    cmds:
      - kluctl deploy -t staging
    desc: "Deploy staging configuration"

  delete-staging:
    cmds:
      - kluctl delete -t staging
    desc: "Render resource yaml with staging values"

  render-production:
    cmds:
      - kluctl render -t production --print-all | yq
    desc: "Render resource yaml with production values"

  deploy-production:
    cmds:
      - kluctl deploy -t production
    desc: "Deploy production configuration"

  delete-production:
    cmds:
      - kluctl delete -t production
    desc: "Render resource yaml with production values"
  
  gcp:create-vpc:
    cmds:
      - gcloud compute networks create ${CLUSTER_NAME} --subnet-mode=custom
    desc: "Create VPC"

  gcp:create-subnet:
    cmds:
      - |
        gcloud compute networks subnets create subnet-1 \
          --network=${CLUSTER_NAME} \
          --region=${GCP_REGION} \
          --range=10.0.0.0/20
    desc: "Create subnet"

  gcp:create-cluster:
    desc: "Create GKE cluster"
    vars:
      GCP_PROJECT_ID: project-b2a5c546-f972-43e5-954
    cmds:
      - |
        gcloud container clusters create ${CLUSTER_NAME} \
          --zone ${GCP_ZONE} \
          --network ${CLUSTER_NAME} \
          --subnetwork subnet-1 \
          --machine-type e2-standard-2 \
          --num-nodes 2 \
          --gateway-api=standard \
          --workload-pool={{.GCP_PROJECT_ID}}.svc.id.goog

  gcp:create-vpc-staging:
    cmds:
      - gcloud compute networks create ${CLUSTER_NAME_STAGING} --subnet-mode=custom
    desc: "Create VPC"

  gcp:create-subnet-staging:
    cmds:
      - |
        gcloud compute networks subnets create subnet-1 \
          --network=${CLUSTER_NAME_STAGING} \
          --region=${GCP_REGION} \
          --range=10.0.0.0/20
    desc: "Create subnet"

  gcp:create-cluster-staging:
    desc: "Create GKE cluster"
    vars:
      GCP_PROJECT_ID: project-b2a5c546-f972-43e5-954
    cmds:
      - |
        gcloud container clusters create ${CLUSTER_NAME_STAGING} \
          --zone ${GCP_ZONE} \
          --network ${CLUSTER_NAME_STAGING} \
          --subnetwork subnet-1 \
          --machine-type e2-standard-2 \
          --num-nodes 2 \
          --gateway-api=standard \
          --workload-pool={{.GCP_PROJECT_ID}}.svc.id.goog

